services:
  sonarqube:
    image: sonarqube:community
    # user: ${CURRENT_UID}
    # depends_on:
    #   - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://localhost:5432/sonar
      SONAR_JDBC_USERNAME: root
      SONAR_JDBC_PASSWORD: 12345678
      SONAR_USERNAME: root
      SONAR_PASSWORD: 12345678
    # volumes:
    #   - ./opt/sonarqube/data:/opt/sonarqube/data
    #   - ./opt/sonarqube/extensions:/opt/sonarqube/extensions
    #   - ./opt/sonarqube/logs:/opt/sonarqube/logs
    network_mode: host
    # ports:
    #   - "9000:9000"
  # db:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: root
  #     POSTGRES_PASSWORD: 12345678
  #   volumes:
  #     - postgresql:/var/lib/postgresql
  #     - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
